### ISSUE TITLE
HOWTO support 6.4.2

### ISSUE THREAD

**Issue by zsdevX** [maliceio/malice-kibana-plugin#6]
Attempting to transfer from https://github.com/maliceio/malice-kibana-plugin/releases/download/v6.4.1/malice-6.4.1.zip
Transferring 59032 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [malice]. Expected [6.4.2]; found [6.4.1]"

**Comment by blacktop** [comment]
Sorry I didn't respond, did you figure it out?  I am now adding support for 6.5.0
