### ISSUE TITLE
What Does It Do?

### ISSUE THREAD

**Issue by wwalker0307** [maliceio/malice-kibana-plugin#9]
Sorry for the ignorance but what does the plugin do?  From the screenshot it looks like it might do file analysis and check online virus signature DBs for a match.  Is there other forms of software dependencies or does the plugin do everything?

**Comment by blacktop** [comment]
So right now it is just a way to look at the malice results in a UI that is like VirusTotals, it supports fuzzy search so you can search for any indicator and it will get you a list of scans that match.

I am working on a new version that is API first, and then the UI will also allow you to submit to malice via the plugin... soon. ;)
